import type { KnowledgeBaseEntry } from '@/types';

export const KNOWLEDGE_BASE: KnowledgeBaseEntry[] = [
  // ═══════════════════════ 珊瑚 ═══════════════════════
  {
    id: 'kb-coral-sps',
    category: 'coral',
    title: '硬骨珊瑚 (SPS) 水质参数',
    content: '硬骨珊瑚对水质要求极为严格，需要稳定的钙、镁、KH 三角平衡。SPS 珊瑚（小多角、鹿角等）是最高难度的珊瑚种类，任何参数波动都可能导致褪色或死亡。',
    params: [
      { name: '钙 (Ca)', value: '400-450', unit: 'ppm', note: '建议 420 为最佳值' },
      { name: '镁 (Mg)', value: '1250-1350', unit: 'ppm', note: '镁是维持钙/碳酸盐平衡的关键' },
      { name: 'KH (碱度)', value: '7-11', unit: '°dH', note: '建议 8-9 为最佳，每日波动不超过 0.5' },
      { name: 'PO₄ (磷酸盐)', value: '<0.03', unit: 'ppm', note: '过高会导致藻类爆发、珊瑚脱色' },
      { name: 'NO₃ (硝酸盐)', value: '<1', unit: 'ppm', note: 'SPS 对硝酸盐极其敏感' },
      { name: '温度', value: '25-26', unit: '°C', note: '波动不超过 ±0.5°C' },
      { name: '盐度', value: '1.023-1.026', unit: 'sg', note: '对应 30-35 ppt' },
      { name: 'pH', value: '8.1-8.4', unit: '', note: '夜间不低于 7.9' },
      { name: '碘 (I₂)', value: '0.04-0.08', unit: 'mg/L', note: '有助于甲壳类和珊瑚骨骼发育' },
      { name: '锶 (Sr)', value: '4-10', unit: 'mg/L', note: '骨骼构成元素' },
    ],
    tags: ['硬骨珊瑚', 'SPS', '钙', '镁', 'KH', '高级玩家'],
  },
  {
    id: 'kb-coral-lps',
    category: 'coral',
    title: '软体/ LPS 珊瑚水质参数',
    content: 'LPS 珊瑚（脑珊瑚、锤珊瑚、大肚泡泡等）比 SPS 更耐受，但仍需维持基本参数稳定。适合中级玩家，外表华丽，颜色丰富。',
    params: [
      { name: '钙 (Ca)', value: '380-450', unit: 'ppm' },
      { name: '镁 (Mg)', value: '1200-1350', unit: 'ppm' },
      { name: 'KH', value: '6-10', unit: '°dH' },
      { name: 'PO₄', value: '<0.1', unit: 'ppm' },
      { name: 'NO₃', value: '<5', unit: 'ppm' },
      { name: '温度', value: '24-27', unit: '°C' },
      { name: 'pH', value: '7.9-8.3', unit: '' },
      { name: '水流', value: '中等', unit: '', note: '避免直吹，珊瑚触手会缩回' },
    ],
    tags: ['LPS', '软体珊瑚', '脑珊瑚', '锤珊瑚', '中级玩家'],
  },
  {
    id: 'kb-coral-nps',
    category: 'coral',
    title: 'NPS 珊瑚（非光合作用）饲养要点',
    content: 'NPS 珊瑚如太阳珊瑚（杯形珊瑚）、炮仗花等，不含共生虫黄藻，完全依靠外源喂食获取能量。饲养难度高，成本大，但极其壮观。',
    params: [
      { name: '光照', value: '弱光/无光', unit: '', note: '它们不需要共生虫黄藻，强光反而有害' },
      { name: '水流', value: '中等', unit: '', note: '帮助带走残渣，但不可过强' },
      { name: '喂食', value: '每周 2-3 次', unit: '', note: '使用珊瑚粮、轮虫、丰年虾幼体、冷冻桡足类' },
      { name: 'NO₃/PO₄', value: '可略高', unit: '', note: '因为它们接受外源营养，但也不能过高' },
      { name: '温度', value: '24-26', unit: '°C' },
    ],
    tags: ['NPS', '太阳珊瑚', '非光合', '喂食', '中级'],
  },
  {
    id: 'kb-coral-acclimation',
    category: 'coral',
    title: '珊瑚入缸驯化方法',
    content: '新购珊瑚直接放入缸中可能因水质差异导致应激。正确的驯化方法能大幅提高存活率。',
    params: [
      { name: '滴流驯化时长', value: '30-60', unit: '分钟', note: '低比重法/参数差异大时需更长时间' },
      { name: '光照适应期', value: '1-2', unit: '周', note: '先放低光区再逐步移到最终位置' },
      { name: '水温匹配', value: '±0.5', unit: '°C以内', note: '新水袋漂浮缸面 15 分钟均温' },
      { name: '检疫期', value: '最少 4 周', unit: '', note: '隔离缸中观察是否携带寄生虫/虫害' },
    ],
    tags: ['珊瑚', '入缸', '驯化', '检疫', '新手'],
  },
  {
    id: 'kb-coral-dosing',
    category: 'coral',
    title: '三元素（Ca/KH/Mg）补充方法',
    content: '海缸珊瑚会持续消耗钙、KH 和镁，需要定期补充。常见方法有双组份补充、钙反应器和石灰水（Kalkwasser）。',
    params: [
      { name: '双组份补充', value: '每日添加', unit: '', note: '操作简单，适合小缸和初学者' },
      { name: '钙反应器', value: '持续补充', unit: '', note: '适合大缸，补充均匀，长期经济' },
      { name: 'Kalkwasser', value: '点滴', unit: '', note: '同时补钙和碱度，还能中和酸性顶水' },
      { name: '消耗速率参考', value: 'SPS缸每100L约20ppm/天', unit: 'Ca', note: '取决于珊瑚量和生长速度' },
    ],
    tags: ['补钙', 'Ca', 'KH', 'Mg', '钙反应器', '双组份'],
  },
  // ═══════════════════════ 鱼类 ═══════════════════════
  {
    id: 'kb-freshwater-community',
    category: 'fish',
    title: '淡水混养社区缸参数',
    content: '淡水社区缸适合灯科、鼠鱼、神仙鱼等温和鱼类混养。选鱼原则：性情温和、体型相近、水质需求相似。',
    params: [
      { name: 'pH', value: '6.5-7.5', unit: '' },
      { name: '温度', value: '23-26', unit: '°C', note: '灯科 24°C 最佳，神仙 26°C 最佳' },
      { name: 'GH', value: '4-12', unit: '°dH' },
      { name: 'KH', value: '3-8', unit: '°dH' },
      { name: 'NO₃', value: '<20', unit: 'ppm' },
      { name: '氨氮', value: '0', unit: 'mg/L', note: '任何可见的氨氮都危险' },
      { name: '亚硝酸', value: '0', unit: 'mg/L' },
    ],
    tags: ['淡水', '社区缸', '灯科', '新手'],
  },
  {
    id: 'kb-freshwater-goldfish',
    category: 'fish',
    title: '金鱼/锦鲤水质参数',
    content: '金鱼是高代谢鱼类，产废量为同体型鱼类的 3-5 倍，对过滤系统要求极高。建议过滤流量为水体 5-10 倍/小时。',
    params: [
      { name: 'pH', value: '7.0-8.0', unit: '' },
      { name: '温度', value: '18-24', unit: '°C', note: '金鱼不需要加热，但骤降温需防白点' },
      { name: 'GH', value: '6-15', unit: '°dH' },
      { name: 'KH', value: '5-12', unit: '°dH' },
      { name: '氨氮', value: '0', unit: 'mg/L' },
      { name: 'NO₃', value: '<40', unit: 'ppm', note: '金鱼可耐受较高硝酸盐，但仍需定期换水' },
      { name: '缸容积建议', value: '每条小金鱼 ≥30L', unit: '', note: '大型金鱼（寿星等）需 ≥80L' },
    ],
    tags: ['金鱼', '锦鲤', '高代谢', '高废物'],
  },
  {
    id: 'kb-freshwater-cichlid',
    category: 'fish',
    title: '非洲三湖慈鲷参数',
    content: '马拉维湖、坦噶尼喀湖、维多利亚湖三大湖慈鲷，需要偏碱性硬水。各湖之间生存条件也有差异。美洲慈鲷（七彩神仙、地图鱼）则需要软酸水。',
    params: [
      { name: 'pH（非洲三湖）', value: '7.8-8.5', unit: '', note: '马湖 8.0-8.5，坦湖 7.8-9.0' },
      { name: 'pH（美洲慈鲷）', value: '6.0-7.5', unit: '', note: '七彩神仙需 5.5-6.5' },
      { name: '温度', value: '24-28', unit: '°C', note: '坦湖 25-27°C，马湖 26-28°C，七彩 28-30°C' },
      { name: 'GH（三湖）', value: '10-25', unit: '°dH', note: '需高硬度' },
      { name: 'KH（三湖）', value: '8-15', unit: '°dH' },
      { name: 'NO₃', value: '<20', unit: 'ppm' },
    ],
    tags: ['慈鲷', '三湖', '硬水', '七彩神仙', '美洲慈鲷'],
  },
  {
    id: 'kb-fish-betta',
    category: 'fish',
    title: '斗鱼（贝塔）饲养参数',
    content: '斗鱼是独居领地性鱼，雄鱼不可混养，但可与温和无鳍鱼同缸。斗鱼有迷宫器，可在水面呼吸空气，但仍需干净水质。',
    params: [
      { name: 'pH', value: '6.5-7.5', unit: '' },
      { name: '温度', value: '26-30', unit: '°C', note: '低于 24°C 容易生病' },
      { name: 'GH', value: '5-20', unit: '°dH', note: '适应性强' },
      { name: '最小缸容', value: '10-20', unit: 'L', note: '越大越好，便于维稳水质' },
      { name: 'NO₃', value: '<20', unit: 'ppm' },
      { name: '换水频率', value: '每周 20-30%', unit: '', note: '小缸需更频繁' },
    ],
    tags: ['斗鱼', '贝塔', '单养', '新手'],
  },
  {
    id: 'kb-fish-discus',
    category: 'fish',
    title: '七彩神仙饲养参数',
    content: '七彩神仙是淡水鱼中要求最高的物种之一，被称为"淡水之王"。需要极软的酸性水，温度偏高，换水极为频繁。',
    params: [
      { name: 'pH', value: '5.5-6.8', unit: '', note: '野生品系需 5.5-6.0，养殖品系可接受 6.5-7.0' },
      { name: '温度', value: '28-32', unit: '°C', note: '低于 27°C 停止进食，低于 25°C 生病' },
      { name: 'GH', value: '1-8', unit: '°dH', note: '越软越好，野生需 <3' },
      { name: 'TDS', value: '50-200', unit: 'ppm', note: '过高水质影响进食和繁殖' },
      { name: '换水频率', value: '每日 20-50%', unit: '', note: '大量喂食和繁殖期需每日换水' },
      { name: '氨氮/亚硝酸', value: '0', unit: 'mg/L' },
    ],
    tags: ['七彩神仙', '淡水之王', '软水', '高温', '高级'],
  },
  {
    id: 'kb-fish-marine-clownfish',
    category: 'fish',
    title: '小丑鱼与海葵共生',
    content: '小丑鱼（公子小丑、透红小丑等）是最受欢迎的海水鱼，与海葵共生。无海葵也可养，但海葵能给其提供庇护所，减少应激。',
    params: [
      { name: '盐度', value: '1.023-1.025', unit: 'sg' },
      { name: '温度', value: '24-27', unit: '°C' },
      { name: '推荐海葵', value: '奶嘴海葵、地毯海葵', unit: '', note: '球形海葵适配多种小丑鱼' },
      { name: '海葵所需光照', value: 'PAR 100-250', unit: 'μmol/m²/s', note: '海葵需要足够的光才能维持' },
      { name: '缸容积', value: '最小 80L', unit: '', note: '含海葵的缸需更多空间' },
      { name: 'NO₃', value: '<10', unit: 'ppm', note: '海葵对高硝酸盐很敏感' },
    ],
    tags: ['小丑鱼', '海葵', '共生', '海水', '新手'],
  },
  {
    id: 'kb-fish-marine-community',
    category: 'fish',
    title: '海水 FOWLR 社区缸参数',
    content: 'FOWLR (Fish Only With Live Rock) 是以鱼和活石为主的混养缸，不需要精确的珊瑚参数，相对容易入门。',
    params: [
      { name: '盐度', value: '1.023-1.025', unit: 'sg' },
      { name: '温度', value: '25-26', unit: '°C' },
      { name: 'pH', value: '8.1-8.3', unit: '' },
      { name: 'KH', value: '7-11', unit: '°dH' },
      { name: 'NO₃', value: '<20', unit: 'ppm' },
      { name: 'PO₄', value: '<0.1', unit: 'ppm' },
    ],
    tags: ['FOWLR', '海水鱼', '社区缸', '新手'],
  },
  // ═══════════════════════ 水草 ═══════════════════════
  {
    id: 'kb-plant-co2',
    category: 'plant',
    title: '水草缸 CO₂ 与光照平衡',
    content: '水草缸的核心是三要素平衡：光照、CO₂、肥料。三者任意失衡都会导致藻爆。强光 + 低 CO₂ = 绿藻爆发；高 CO₂ + 低光 = 浪费。',
    params: [
      { name: 'CO₂ 浓度', value: '20-30', unit: 'ppm', note: '使用检测液或长期监测器确认' },
      { name: '光照强度（低光水草）', value: '10-20', unit: 'PAR', note: '爪哇莫丝、小榕、铁皇冠' },
      { name: '光照强度（中光水草）', value: '30-50', unit: 'PAR', note: '椒草、皇冠草等' },
      { name: '光照强度（强光水草）', value: '50-100+', unit: 'PAR', note: '红色系、细叶有茎草' },
      { name: 'KH', value: '3-8', unit: '°dH', note: '低 KH 下 pH 波动更大' },
      { name: 'pH（CO₂ 注入后）', value: '6.0-7.0', unit: '' },
      { name: '换水频率', value: '每周 30-50%', unit: '', note: '去除多余肥料，防止藻类' },
    ],
    tags: ['水草', 'CO₂', '光照', '肥料', '藻类控制'],
  },
  {
    id: 'kb-plant-fertilizer',
    category: 'plant',
    title: '水草施肥指南：大量元素与微量元素',
    content: '水草需要大量元素（N、P、K）和微量元素（Fe、Mn、B 等）。根据"最小量因子定律"，生长受限于最缺乏的元素。',
    params: [
      { name: '氮 (NO₃)', value: '5-30', unit: 'ppm', note: '不足时叶片变黄从老叶开始' },
      { name: '磷 (PO₄)', value: '0.5-3', unit: 'ppm', note: '不足时叶片变小、暗淡' },
      { name: '钾 (K)', value: '5-20', unit: 'ppm', note: '不足时出现针孔叶片' },
      { name: '铁 (Fe)', value: '0.1-0.5', unit: 'ppm', note: '不足时新叶泛黄（叶脉绿但叶面黄）' },
      { name: '施肥时间', value: '开灯前或开灯时', unit: '', note: '光合作用开始时养分利用效率最高' },
    ],
    tags: ['水草', '施肥', '氮', '磷', '钾', '铁', '微量元素'],
  },
  {
    id: 'kb-plant-algae',
    category: 'plant',
    title: '常见藻类识别与控制',
    content: '藻类是水草缸最大的敌人，不同类型的藻对应不同的问题。正确识别藻类是解决问题的第一步。',
    params: [
      { name: '绿斑藻（GSA）', value: '低磷 + 光照强', unit: '', note: '补磷（PO₄ ≥0.5ppm），减光' },
      { name: '黑毛藻（BBA）', value: 'CO₂ 不稳定', unit: '', note: '稳定 CO₂，提高流速，用液体碳素点涂' },
      { name: '丝藻', value: '强光 + 高氮', unit: '', note: '减光、适当引入飞狐鱼' },
      { name: '蓝藻（BGA）', value: '低氮 + 低流速', unit: '', note: '补氮，增加水流，遮光 3 天' },
      { name: '褐藻（硅藻）', value: '新缸常见', unit: '', note: '开缸初期正常现象，稳定后自行消退' },
    ],
    tags: ['藻类', '绿斑藻', '黑毛藻', '蓝藻', '水草', '防藻'],
  },
  // ═══════════════════════ 水质处理 ═══════════════════════
  {
    id: 'kb-water-ammonia-cycle',
    category: 'water',
    title: '氮循环与开缸流程',
    content: '新缸必须完成氮循环才能放鱼，通常需要 2-6 周。氮循环的建立是水族最基础也最重要的知识。硝化细菌（亚硝酸菌和硝酸菌）是核心角色。',
    params: [
      { name: '第一阶段', value: '氨氮上升（第 1-5 天）', unit: '', note: '投放诱饵（鱼食/纯氨），启动硝化系统' },
      { name: '第二阶段', value: '亚硝酸峰值（第 7-14 天）', unit: '', note: '亚硝酸菌开始工作；此时 NO₂ 可高达 5mg/L' },
      { name: '第三阶段', value: '硝酸盐出现（第 14-42 天）', unit: '', note: '硝酸菌建立，NH₃和NO₂ 归零' },
      { name: '入缸标准', value: 'NH₃=0, NO₂=0', unit: '', note: 'NO₃ 上升是正常的，换水即可控制' },
      { name: '加速方法', value: '使用老滤材 / 硝化菌液', unit: '', note: '可缩短至 1-2 周' },
    ],
    tags: ['氮循环', '开缸', '新手必读', '硝化系统', '氨氮', '亚硝酸'],
  },
  {
    id: 'kb-water-change',
    category: 'water',
    title: '换水频率与换水量指南',
    content: '换水是最基础也最有效的水质维护手段。换水能稀释有害物质（NO₃、PO₄）、补充微量元素和矿物质。',
    params: [
      { name: '普通淡水缸', value: '每周 20-30%', unit: '', note: '鱼量适中的成熟缸' },
      { name: '高密度/喂食频繁', value: '每周 30-50%', unit: '', note: '金鱼缸、七彩神仙缸' },
      { name: '海水缸（鱼缸）', value: '每 2 周 20-25%', unit: '', note: '需预先配置海水' },
      { name: '海水缸（珊瑚缸）', value: '每月 10-15%', unit: '', note: '配合补剂维持参数稳定' },
      { name: '新水温差', value: '±0.5', unit: '°C', note: '温差过大导致应激' },
      { name: '最大单次换水量', value: '50%', unit: '', note: '超过 50% 可能破坏硝化系统稳定性' },
    ],
    tags: ['换水', '水质维护', '频率', '换水量'],
  },
  {
    id: 'kb-water-salt-mix',
    category: 'water',
    title: '海水配置与盐度测量',
    content: '海水的配置需要使用专业人工海盐，不可使用食用盐。盐度的精确测量是海水缸成功的基础。',
    params: [
      { name: '推荐盐度（珊瑚缸）', value: '1.025-1.026', unit: 'sg', note: '对应 34-35 ppt' },
      { name: '推荐盐度（鱼缸）', value: '1.020-1.025', unit: 'sg' },
      { name: '每 1000L 加盐量', value: '约 35', unit: 'kg', note: '达到 1.025 sg' },
      { name: '配置用水', value: 'RO/DI 纯水', unit: '', note: '不可使用自来水，矿物质比例不对' },
      { name: '测量工具', value: '折射仪或比重计', unit: '', note: '折射仪更精准，但需定期校准' },
    ],
    tags: ['海水', '盐度', '配水', '人工海盐', 'RO水'],
  },
  {
    id: 'kb-water-ro',
    category: 'water',
    title: 'RO 纯水系统使用指南',
    content: 'RO（反渗透）纯水系统能去除自来水中 95%+ 的矿物质、重金属、氯、氟等。是海水缸和水草缸的标配，也越来越多地被淡水缸玩家使用。',
    params: [
      { name: 'RO 水 TDS', value: '<10', unit: 'ppm', note: '越低越好，低于 5ppm 为优秀' },
      { name: '滤芯更换（前置棉）', value: '每 3-6 个月', unit: '', note: '视水质情况' },
      { name: '滤芯更换（RO 膜）', value: '每 1-2 年', unit: '', note: '当产水 TDS 超过进水 10% 时更换' },
      { name: 'DI 树脂更换', value: 'TDS > 5ppm 时', unit: '', note: '可再生或直接更换' },
      { name: '纯水再矿化', value: '根据目标水质加矿化液', unit: '', note: '淡水缸需加 GH/KH 调节剂' },
    ],
    tags: ['RO水', '纯水', 'TDS', '滤芯', '水处理'],
  },
  {
    id: 'kb-water-chlorine',
    category: 'water',
    title: '自来水除氯处理方法',
    content: '自来水中含有氯和氯胺，会杀死硝化细菌和鱼类的鳃部细胞。换水前必须处理。',
    params: [
      { name: '大苏打（硫代硫酸钠）', value: '每 10L 加 1g', unit: '', note: '只能去除游离氯，不能去除氯胺' },
      { name: '水质稳定液', value: '按说明书', unit: '', note: 'Seachem Prime 等产品可同时中和氯/氯胺/重金属' },
      { name: '曝气法', value: '充气 24 小时', unit: '', note: '只能去除游离氯，对氯胺无效' },
      { name: '活性炭过滤', value: '连续通过', unit: '', note: '可以有效去除氯和氯胺' },
    ],
    tags: ['自来水', '除氯', '氯胺', '水处理', '新手'],
  },
  // ═══════════════════════ 设备 ═══════════════════════
  {
    id: 'kb-equipment-protein-skimmer',
    category: 'equipment',
    title: '蛋白质分离器（蛋分）选型与维护',
    content: '蛋分是海缸最重要的过滤设备，通过细密气泡将有机废物带出水体，在有机物分解为氨氮前就将其去除，从源头减少污染负荷。',
    params: [
      { name: '处理量', value: '缸体水体 1-2 倍/小时', unit: '', note: '海水混养缸取高值' },
      { name: '安装位置', value: '背滤仓第一格', unit: '', note: '建议水位 20-25cm' },
      { name: '出泡状态', value: '茶色偏干', unit: '', note: '太干（黑色）= 太浓，太湿（淡黄/清澈）= 废物少' },
      { name: '清洗频率', value: '每 1-2 周', unit: '', note: '清洁蛋分杯，防止效率下降' },
      { name: '推荐品牌', value: 'Reef Octopus / Deltec / Bubble Magus / Nyos', unit: '' },
    ],
    tags: ['蛋分', '蛋白质分离器', '海缸', '过滤', '设备'],
  },
  {
    id: 'kb-equipment-lighting',
    category: 'equipment',
    title: '珊瑚灯选型：PAR 与光谱',
    content: '珊瑚灯不是越亮越好，关键在于正确的 PAR 值和覆盖足够的光谱宽度。蓝光（420-430nm, 450-470nm）驱动珊瑚荧光蛋白，白光（6500K）提供光合能量。',
    params: [
      { name: 'SPS 所需 PAR', value: '200-400', unit: 'μmol/m²/s', note: '深水摆放的 SPS 可接受更低 PAR' },
      { name: 'LPS 所需 PAR', value: '50-150', unit: 'μmol/m²/s' },
      { name: '蓝光比例', value: '60-80%', unit: '', note: '蓝光为主，配合适量白光' },
      { name: '每日光照时长', value: '8-10', unit: '小时', note: '建议程序模拟日出日落渐变' },
      { name: '推荐品牌', value: 'Radion / Hydra / AI Blade / Mars', unit: '' },
    ],
    tags: ['灯具', 'PAR', '光谱', '蓝光', '珊瑚灯'],
  },
  {
    id: 'kb-equipment-filter',
    category: 'equipment',
    title: '过滤系统选型指南',
    content: '过滤系统是鱼缸生命维持的核心。生化过滤（硝化细菌）、物理过滤（机械截留）、化学过滤（活性炭等）三合一才是完整过滤。',
    params: [
      { name: '过滤流量建议（淡水）', value: '水体 5-10 倍/小时', unit: '', note: '金鱼、高密度缸取高值' },
      { name: '过滤流量建议（海水）', value: '水体 10-20 倍/小时', unit: '' },
      { name: '背滤', value: '一体化，外观整洁', unit: '', note: '适合中小型缸，维护空间有限' },
      { name: '底滤', value: '容量大，可定制', unit: '', note: '适合大型缸，分格更灵活' },
      { name: '外置过滤桶', value: '安静，适合淡水缸', unit: '', note: '不适合海水/高档珊瑚缸' },
      { name: '滤材更换', value: '滤棉每月，活性炭每月', unit: '', note: '生化环、陶瓷圈尽量不换' },
    ],
    tags: ['过滤', '背滤', '底滤', '外挂', '外桶', '设备'],
  },
  {
    id: 'kb-equipment-heater',
    category: 'equipment',
    title: '加热棒选型与温控策略',
    content: '稳定的水温对鱼类和珊瑚极为重要。昼夜温差超过 2°C 会导致鱼类应激，超过 4°C 可能致死珊瑚。',
    params: [
      { name: '功率建议', value: '每 10L 约 3-5W', unit: '', note: '大缸双棒分置效果更均匀' },
      { name: '安全措施', value: '双温控（恒温器+独立控温）', unit: '', note: '防止加热棒失控过热（煮缸）' },
      { name: '安装位置', value: '水流强处，斜放', unit: '', note: '确保热量均匀扩散' },
      { name: '推荐品牌', value: 'Eheim / Fluval / Inkbird（控温器）', unit: '' },
      { name: '夏季降温', value: '冷水机 / 风扇蒸发降温', unit: '', note: '风扇会加快蒸发导致盐度升高，需补淡水' },
    ],
    tags: ['加热棒', '温控', '煮缸', '冷水机', '设备'],
  },
  {
    id: 'kb-equipment-wavemaker',
    category: 'equipment',
    title: '造浪泵（循环泵）配置',
    content: '良好的水流能保证充氧、带走废物、防止死角、让珊瑚得到食物。不同鱼类和珊瑚对水流需求差异很大。',
    params: [
      { name: '海水珊瑚缸总流量', value: '水体 30-50 倍/小时', unit: '' },
      { name: 'SPS 区域流速', value: '高流速，随机波动', unit: '', note: '使用造浪模式' },
      { name: 'LPS 区域流速', value: '中等，避免直吹', unit: '' },
      { name: '淡水鱼缸流量', value: '水体 5-15 倍/小时', unit: '' },
      { name: '死角处理', value: '底部反向补流', unit: '', note: '防止废物堆积' },
    ],
    tags: ['造浪泵', '循环泵', '水流', '设备'],
  },
  {
    id: 'kb-equipment-uv',
    category: 'equipment',
    title: 'UV 杀菌灯使用指南',
    content: 'UV 紫外线杀菌灯能有效杀死水中漂浮的细菌、藻类孢子和部分寄生虫。对已附着的鱼体寄生虫效果有限。',
    params: [
      { name: '流速要求', value: '慢，与灯管功率匹配', unit: '', note: '流速太快杀菌不彻底' },
      { name: '灯管寿命', value: '约 6-12 个月', unit: '', note: '到期必须更换，紫外线强度会衰减' },
      { name: '适用场景', value: '预防绿水、辅助防病', unit: '' },
      { name: '不适用场景', value: '治疗体表寄生虫', unit: '', note: 'UV 只能杀游离期的寄生虫' },
      { name: '注意事项', value: '不可直视，更换时断电', unit: '', note: '紫外线对眼睛有害' },
    ],
    tags: ['UV', '杀菌灯', '绿水', '设备'],
  },
  {
    id: 'kb-equipment-ato',
    category: 'equipment',
    title: '自动补水（ATO）系统',
    content: '海水缸蒸发会导致盐度升高，ATO 系统能自动补充纯水（RO水）维持盐度稳定，是海水缸的必备辅助设备。',
    params: [
      { name: '工作原理', value: '液位传感器检测水位下降后自动泵入纯水', unit: '' },
      { name: '补水频率', value: '视蒸发量，通常每日 1-3L（100L缸）', unit: '' },
      { name: '补水来源', value: '必须使用 RO 纯水（TDS <5）', unit: '', note: '不可用海水或自来水' },
      { name: '防护措施', value: '设置最大补水量上限', unit: '', note: '防止传感器故障导致过度补水' },
    ],
    tags: ['ATO', '自动补水', '盐度', '设备'],
  },
  // ═══════════════════════ 鱼病 ═══════════════════════
  {
    id: 'kb-disease-ich',
    category: 'disease',
    title: '白点病（小瓜虫）识别与治疗',
    content: '白点病是最常见的鱼病，由 Ichthyophthirius multifiliis（淡水）或 Cryptocaryon irritans（海水）引起。生命周期分为包囊期→滋养体→自由游泳期，只有自由游泳期可被杀灭。',
    params: [
      { name: '症状', value: '体表白色小点（1mm），摩擦，急喘', unit: '' },
      { name: '淡水治疗', value: '升温 30°C + 亚甲基蓝/白点净', unit: '', note: '维持 7-14 天，不可骤然降温' },
      { name: '海水治疗', value: '铜剂 / 低比重法（1.009-1.011）/ UV', unit: '', note: '铜剂对无脊椎动物致命，需隔离治疗' },
      { name: '主缸处理', value: '无鱼空置 6-8 周', unit: '', note: '寄生虫因无宿主而死亡' },
      { name: '预防', value: '新鱼检疫 4 周以上', unit: '', note: '永远是最有效的方案' },
    ],
    tags: ['白点病', '小瓜虫', '鱼病', '治疗', '预防'],
  },
  {
    id: 'kb-disease-velvet',
    category: 'disease',
    title: '天鹅绒病（卵圆虫/胡椒病）',
    content: '天鹅绒病（Amyloodinium）比白点病更危险，进展迅速，1-2 天内可导致全缸鱼死亡。早期发现和快速隔离至关重要。',
    params: [
      { name: '症状', value: '金色/锈色粉末状覆盖皮肤，用手电斜照可见', unit: '' },
      { name: '行为表现', value: '摩擦，急喘，聚集在通气口附近', unit: '' },
      { name: '海水治疗', value: '铜剂（自由离子铜 0.15-0.20ppm）', unit: '' },
      { name: '淡水治疗', value: '福尔马林 / 低浓度铜剂', unit: '' },
      { name: '紧急措施', value: '立即隔离所有鱼，主缸空置 4-6 周', unit: '' },
    ],
    tags: ['天鹅绒', '卵圆虫', '鱼病', '紧急', '海水'],
  },
  {
    id: 'kb-disease-fin-rot',
    category: 'disease',
    title: '烂鳍病与细菌感染',
    content: '烂鳍病多由细菌（气单胞菌、假单胞菌等）引起，常见于水质差、应激后或受伤后的鱼。',
    params: [
      { name: '症状', value: '鳍条边缘发白、溃烂、缩短', unit: '' },
      { name: '原因', value: '水质差（高氨氮/NO₃），应激，啃咬', unit: '' },
      { name: '治疗方案', value: '先改善水质，再用抗菌药（如呋喃唑酮）', unit: '', note: '水质不改善，用药也无效' },
      { name: '药浴', value: '盐水浴（淡水鱼）', unit: '', note: '5g/L 盐水药浴 5-10 分钟，连续 3 天' },
      { name: '隔离治疗', value: '建议', unit: '', note: '防止蔓延，主缸继续大量换水' },
    ],
    tags: ['烂鳍病', '细菌感染', '鱼病', '治疗'],
  },
  {
    id: 'kb-disease-dropsy',
    category: 'disease',
    title: '松鳞病（水肿/竖鳞病）',
    content: '松鳞病（Dropsy）俗称"松果鱼"，鳞片竖立，腹腔积水，是多种内部器官衰竭的共同症状，死亡率极高，一般被视为晚期症状。',
    params: [
      { name: '症状', value: '鳞片外张呈松果状，腹部肿胀，鱼体消瘦', unit: '' },
      { name: '原因', value: '细菌性器官感染、病毒、饮食/遗传因素', unit: '' },
      { name: '治疗方案', value: 'Kanamycin + Metronidazole 联合治疗', unit: '', note: '早期有一定成功率，晚期几乎无效' },
      { name: '预后', value: '存活率低，人道安乐死是选项', unit: '' },
      { name: '预防', value: '维持良好水质，避免过度喂食', unit: '' },
    ],
    tags: ['松鳞病', '竖鳞', '水肿', '鱼病'],
  },
  {
    id: 'kb-disease-ich-marine',
    category: 'disease',
    title: '海水白点（cryptocaryon）深度治疗',
    content: '海水白点与淡水白点是不同的寄生虫，生命周期更长（28 天），治疗难度更大。治疗需要彻底清空主缸鱼只。',
    params: [
      { name: '生命周期', value: '约 28-30 天（25°C）', unit: '', note: '升温可加速至 14 天' },
      { name: '铜剂治疗', value: '维持 0.35ppm 自由铜浓度', unit: '', note: '持续 21-28 天，用铜离子测试剂每日检测' },
      { name: '低比重法', value: '盐度降至 1.009，维持 6-8 周', unit: '', note: '对珊瑚缸无法使用' },
      { name: '主缸空置', value: '无宿主空置 76+ 天（25°C）', unit: '', note: '温度越低，空置时间越长' },
      { name: '检疫缸', value: '裸缸 + UV + 可高流速', unit: '', note: '不放活石，方便铜剂维持有效浓度' },
    ],
    tags: ['海水白点', '珊瑚虫', '铜剂', '海水', '鱼病'],
  },
];

export function searchKnowledge(query: string, category?: string): KnowledgeBaseEntry[] {
  const q = query.toLowerCase();
  return KNOWLEDGE_BASE.filter((entry) => {
    if (category && entry.category !== category) return false;
    return (
      entry.title.toLowerCase().includes(q) ||
      entry.content.toLowerCase().includes(q) ||
      entry.tags.some((t) => t.toLowerCase().includes(q)) ||
      entry.params?.some((p) => p.name.toLowerCase().includes(q) || p.note?.toLowerCase().includes(q))
    );
  });
}

export function getByCategory(category: string): KnowledgeBaseEntry[] {
  return KNOWLEDGE_BASE.filter((e) => e.category === category);
}
